# Generated by Django 3.1.4 on 2021-01-01 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_everyday_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckHab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(default=django.utils.timezone.now, max_length=100)),
                ('check_hour', models.IntegerField()),
                ('check_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_everyday_app.habbit')),
            ],
        ),
    ]
