# Generated by Django 3.1.4 on 2021-01-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_everyday_app', '0002_checkhab'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkhab',
            name='check_method',
            field=models.CharField(default='ox', max_length=10),
        ),
        migrations.AddField(
            model_name='habbit',
            name='hab_method',
            field=models.CharField(default='ox', max_length=10),
        ),
        migrations.AlterField(
            model_name='checkhab',
            name='check_title',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='my_everyday_app.habbit'),
        ),
    ]
